/*
 * Copyright (C) 2004 by StreetFire Sound Labs
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * $Id: GarpTimeoutMessage.java,v 1.1 2005/02/22 03:44:26 stephen Exp $
 */

package com.redrocketcomputing.havi.system.cmm.ip.garp;

import org.havi.system.types.HaviByteArrayInputStream;
import org.havi.system.types.HaviByteArrayOutputStream;
import org.havi.system.types.HaviMarshallingException;
import org.havi.system.types.HaviUnmarshallingException;

/**
 * Timeout GARP message generated by the GARP socket reader
 *
 * @author stephen Jul 23, 2003
 * @version 1.0
 *
 */
class GarpTimeoutMessage extends GarpMessage
{
  public final static int MARSHAL_TYPE = 0;

  /**
   * Constructor for GarpTimeoutMessage.
   */
  public GarpTimeoutMessage()
  {
    super();
  }

  /**
   * Constructor for GarpTimeoutMessage.
   * @param hbais The input stream to construct the message
   * @throws HaviUnmarshallingException Thrown with a bad message format is detected
   */
  public GarpTimeoutMessage(HaviByteArrayInputStream hbais) throws HaviUnmarshallingException
  {
    // Forward
    unmarshal(hbais);
  }

  /**
   * @see java.lang.Object#clone()
   */
  protected Object clone() throws CloneNotSupportedException
  {
    throw new CloneNotSupportedException();
  }

  /**
   * @see java.lang.Object#equals(Object)
   */
  public boolean equals(Object o)
  {
    // Only check type
    return (o instanceof GarpTimeoutMessage);
  }

  /**
   * @see java.lang.Object#hashCode()
   */
  public int hashCode()
  {
    return GarpTimeoutMessage.class.hashCode();
  }

  /**
   * @see org.havi.system.types.Marshallable#marshal(HaviByteArrayOutputStream)
   */
  public void marshal(HaviByteArrayOutputStream hbaos) throws HaviMarshallingException
  {
    // Super class
    super.marshal(hbaos);
  }

  /**
   * @see org.havi.system.types.Marshallable#unmarshal(HaviByteArrayInputStream)
   */
  public void unmarshal(HaviByteArrayInputStream hbais) throws HaviUnmarshallingException
  {
    // Super class unmarshal
    super.unmarshal(hbais);
  }

  /**
   * @see com.redrocketcomputing.havi.system.cmm.ip.garp.GarpMessage#dispatch(GarpMessageHandler)
   */
  public void dispatch(GarpMessageHandler handler)
  {
    // Forward to the handler
    handler.handleTimeout();
  }

  /**
   * @see java.lang.Object#toString()
   */
  public String toString()
  {
    return "GarpTimeoutMessage";
  }

}
